trigger:
  branches:
    include:
    - release
variables:
  WindowsContainerImage: 'onebranch.azurecr.io/windows/ltsc2022/vse2022:latest'
resources:
  repositories:
  - repository: templates
    type: git
    name: OneBranch.Pipelines/GovernedTemplates
    ref: refs/heads/main
extends:
  template: v2/OneBranch.Official.CrossPlat.yml@templates
  parameters:
    featureFlags:
      WindowsHostVersion: 1ESWindows2022
    stages:
    - stage: build
      jobs:
      - job: main
        pool:
          type: windows
        variables:
          ob_outputDirectory: 'dist'
        steps:
        - pwsh: |
            cd .\.build
            .\Build.ps1
          displayName: "Build Script"
        - task: onebranch.pipeline.signing@1
          condition: and(succeeded(), ne (variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranch'], 'refs/heads/release'))
          inputs:
            command: 'sign'
            signing_profile: 'external_distribution'
            files_to_sign: '*.ps1'
            search_root: 'dist'
        - pwsh: |
            cd .\.build
            .\BuildScriptVersions.ps1
          displayName: "Build ScriptVersions.txt"
        - pwsh: |
            Get-Content dist\ScriptVersions.txt
          displayName: "Display Script Versions file"
        - pwsh: |
            $tag = "v$((Get-Date).ToString(`"yy.MM.dd.HHmm`"))"
            Write-Host "##vso[task.setvariable variable=ReleaseTagValue]$tag"
            (Get-Content .\dist\ScriptVersions.txt) -replace '^(\S+.ps1)', ('[$1](https://github.com/microsoft/CSS-Exchange/releases/download/' + $tag + '/$1)') | Out-File dist\ScriptVersions.txt
            Get-Content dist\ScriptVersions.txt
          displayName: "Setting Script Versions text file"
        - task: GitHubRelease@0
          displayName: 'Create GitHub Release - Draft'
          condition: and(succeeded(), ne (variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranch'], 'refs/heads/release'))
          inputs:
            gitHubConnection: 'github.com_bill-long'
            repositoryName: microsoft/CSS-Exchange
            action: create
            tagSource: manual
            tagPattern: 'v[0-9].[0-9].[0-9].[0-9]'
            tag: $(ReleaseTagValue)
            title: $(ReleaseTagValue)
            releaseNotesSource: 'file'
            releaseNotesFile: dist\ScriptVersions.txt
            assets: |
              dist\*.ps1
              dist\*.nse
              dist\*.zip
              dist\*.txt
              dist\*.csv
            addChangeLog: true
            isDraft: true
        - task: GitHubRelease@0
          displayName: 'Publish GitHub Release'
          condition: and(succeeded(), ne (variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranch'], 'refs/heads/release'))
          inputs:
            gitHubConnection: 'github.com_bill-long'
            repositoryName: microsoft/CSS-Exchange
            action: edit
            tagSource: manual
            tagPattern: 'v[0-9].[0-9].[0-9].[0-9]'
            tag: $(ReleaseTagValue)
            title: $(ReleaseTagValue)
            releaseNotesSource: 'file'
            releaseNotesFile: dist\ScriptVersions.txt
            assetUploadMode: replace
            addChangeLog: true
            isDraft: false
