# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

<#
.SYNOPSIS
    Maps the full cascading impact of a changed file using the build system dependency XML.
.DESCRIPTION
    Reads the dependency XML files generated by Build.ps1 and walks the full
    dependency chain to find all scripts affected by a change. Uses BFS to
    handle arbitrary depth chains.
.PARAMETER TargetPath
    The path to the changed file (relative or absolute).
.PARAMETER BuildFirst
    If specified, runs Build.ps1 to regenerate dependency XML before analysis.
.EXAMPLE
    .\Get-DependencyCascade.ps1 -TargetPath "Shared\LoggerFunctions.ps1"
.EXAMPLE
    .\Get-DependencyCascade.ps1 -TargetPath "Shared\LoggerFunctions.ps1" -BuildFirst
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [string]$TargetPath,

    [switch]$BuildFirst
)

# cspell:ignore toplevel
try {
    $repoRoot = (git rev-parse --show-toplevel 2>$null)
    if ($repoRoot) {
        $repoRoot = (Resolve-Path $repoRoot).Path
    }
} catch {
    $repoRoot = $null
}
if (-not $repoRoot) {
    $repoRoot = (Get-Item "$PSScriptRoot\..\..\..").FullName
}
$distFolder = Join-Path $repoRoot "dist"

if ($BuildFirst) {
    Write-Host "Running Build.ps1 to regenerate dependency XML..."
    try {
        & "$repoRoot\.build\Build.ps1" -ErrorAction Stop
    } catch {
        Write-Error "Build.ps1 failed: $_. Cannot proceed with stale dependency data."
        return
    }
}

$dependentXml = Join-Path $distFolder "dependentHashtable.xml"
$dependencyXml = Join-Path $distFolder "dependencyHashtable.xml"

if (-not (Test-Path $dependentXml) -or -not (Test-Path $dependencyXml)) {
    Write-Error "Dependency XML files not found in $distFolder. Run .build/Build.ps1 first."
    return
}

$dependentHashtable = Import-Clixml -Path $dependentXml

# Resolve target path — handle both relative and absolute paths
if ([System.IO.Path]::IsPathRooted($TargetPath)) {
    $resolvedTarget = (Resolve-Path $TargetPath -ErrorAction SilentlyContinue).Path
} else {
    $resolvedTarget = (Resolve-Path (Join-Path $repoRoot $TargetPath) -ErrorAction SilentlyContinue).Path
}
if (-not $resolvedTarget) {
    Write-Error "Target file not found: $TargetPath"
    return
}

# Level 1: Direct callers
$directCallers = @()
if ($dependentHashtable.ContainsKey($resolvedTarget)) {
    $directCallers = $dependentHashtable[$resolvedTarget]
    if ($null -eq $directCallers) { $directCallers = @() }
    if ($directCallers -isnot [array]) { $directCallers = @($directCallers) }
}

# All levels: BFS cascade
$allDependents = [System.Collections.Generic.HashSet[string]]::new()
$queue = [System.Collections.Generic.Queue[string]]::new()
$directCallers | ForEach-Object { $queue.Enqueue($_); $null = $allDependents.Add($_) }
while ($queue.Count -gt 0) {
    $current = $queue.Dequeue()
    if ($dependentHashtable.ContainsKey($current)) {
        $deps = $dependentHashtable[$current]
        if ($null -eq $deps) { continue }
        if ($deps -isnot [array]) { $deps = @($deps) }
        foreach ($dep in $deps) {
            if ($allDependents.Add($dep)) {
                $queue.Enqueue($dep)
            }
        }
    }
}

$cascadingOnly = $allDependents | Where-Object { $_ -notin $directCallers }
if ($null -eq $cascadingOnly) { $cascadingOnly = @() }
if ($cascadingOnly -isnot [array]) { $cascadingOnly = @($cascadingOnly) }

# Root/released scripts
$rootScripts = $allDependents | Where-Object {
    -not $dependentHashtable.ContainsKey($_)
}
if ($null -eq $rootScripts) { $rootScripts = @() }
if ($rootScripts -isnot [array]) { $rootScripts = @($rootScripts) }

# Report
Write-Host ""
Write-Host "## Dependency Impact Analysis" -ForegroundColor Cyan
Write-Host ""
Write-Host "Changed File: $TargetPath"
Write-Host ""

if ($allDependents.Count -eq 0) {
    Write-Host "Target is a root/entry-point script with no dependents." -ForegroundColor Green
    Write-Host "Changes affect only this file."
} else {
    Write-Host "### Level 1: Direct Callers ($($directCallers.Count) scripts)" -ForegroundColor Yellow
    $directCallers | ForEach-Object { Write-Host "  - $($_.Replace($repoRoot, '').TrimStart('\', '/'))" }
    Write-Host ""
    Write-Host "### Level 2+: Cascading Dependents ($($cascadingOnly.Count) scripts)" -ForegroundColor Yellow
    $cascadingOnly | ForEach-Object { Write-Host "  - $($_.Replace($repoRoot, '').TrimStart('\', '/'))" }
    Write-Host ""
    Write-Host "### Root Scripts Affected ($($rootScripts.Count) released scripts)" -ForegroundColor Yellow
    $rootScripts | ForEach-Object { Write-Host "  - $($_.Replace($repoRoot, '').TrimStart('\', '/'))" }
    Write-Host ""
    Write-Host "### Total Impact" -ForegroundColor Cyan
    Write-Host "  - Direct: $($directCallers.Count) scripts"
    Write-Host "  - Cascading: $($cascadingOnly.Count) scripts"
    Write-Host "  - Root/Released: $($rootScripts.Count) scripts"
}
