name: Limit Pull Requests

on:
  pull_request:
    branches:
      - microsoft:release

jobs:
  limit_release_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: bill-long/action-pr-limits@v1.0
        with:
          allowlist: |
            microsoft:main
